### ISSUE TITLE
Discriminator should train more than generator

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [sdv-dev/CTGAN#101]
The CTGAN does not implement the extra update iterations of the critic, when compared to the original implementation of WGAN and WGAN-GP. Is this intentional? In my experiments, I have seen that sometimes the generator becomes too powerful and exploits the discriminator. I think this might be improved by implementing the critic extra updates, compared to the generator. 

![image](https://user-images.githubusercontent.com/9077462/100898135-bc277600-34c0-11eb-85b3-60664794f56c.png)
From the paper, we see the critic is updated 5 times more compared to the generator.

**Comment by Baukebrenninkmeijer** [comment]
@csala I can create a PR for this if you like.

**Comment by fealho** [comment]
Good suggestion! As long as you add the number of iterations as a hyperparameter, I'm all for it. @csala

**Comment by shreyanshs** [comment]
Yes I have also seen the same thing as @Baukebrenninkmeijer describes. This suggestion should definitely serve as an improvement.

**Comment by Baukebrenninkmeijer** [comment]
Yeah, indeed. I think it's most suited in the `.fit` function.

**Comment by csala** [comment]
I like the suggestion @Baukebrenninkmeijer, and a PR would be very welcome !

Regarding where to put the argument, I'd prefer to add it as a hyperparameter, as @fealho suggested. In the `fit` method we should try to keep only the arguments that relate to the data which the model is being fitted to, and then have all the hyperparameters that control the learning process in the `__init__`.

Also, I would add a default value of 1 for now so that by default the behavior is the same that we had before while still having the possibility to tweak the value to higher numbers.

**Comment by csala** [comment]
> Regarding where to put the argument, I'd prefer to add it as a hyperparameter, as @fealho suggested. In the `fit` method we should try to keep only the arguments that relate to the data which the model is being fitted to, and then have all the hyperparameters that control the learning process in the `__init__`.

I just opened #102 too, since the `log_frequency` is escaping a bit this abstraction.
