### ISSUE TITLE
Link to R package

### ISSUE THREAD

**Issue by kevinykuo** [sdv-dev/CTGAN#11]
I put together an R package to help broaden the reach of y'all's excellent work at https://github.com/kasaai/ctgan, which also powers a short (insurance) industry-specific application paper. Wanted to see if you'd like to link to the package in the `README` for the useRs that stumble upon the repo :)

@leix28 @csala

**Comment by csala** [comment]
Great contribution @kevinykuo !

I was just reviewing your project before adding the link to the README and noticed that you are using an old version of the code.

Yesterday we released a new version, with a cleaner Python API and broader support for discrete variables, so I think it would be better if you replaced the current installation and the code copy with a simple `ctgan==0.2.0` install from PyPI (use plain pip instead of conda). If you do this you should be able to also remove all the other dependencies (numpy, scipy...), as they will be pulled alongside `ctgan` by `pip`.

Also notice that we moved `epochs` from `__init__` to `fit`, as you suggested, but we kept `batch_size` in the `__init__`, as this is something that gets stored in the instance and used later on when sampling. So maybe it would be a good idea if you mirrored the same API structure, so both implementations are consistent with each other?

Also, keep an eye on the releases, as other things will be added soon as well (like the save/load functionality)

**Comment by kevinykuo** [comment]
Yep I have been watching the repo, and will refactor accordingly. There were some hacks I had to make to get it to work with R. Ideally we can just grab ctgan from pip to lessen maintenance burden :)

I'll keep an eye out on new features, and ensure consistency as much as possible to reduce friction for teams working with different APIs. Note that the R package currently supports save/load already, and we need to have a custom implementation there since we also serialize R-specific metadata. This is partly because we also made the design decision to infer discrete columns from column types, which is more Rtistic (by convention, categorical variables are factors or characters.)

**Comment by kevinykuo** [comment]
@csala I was able to cleanly remove the inline hacks and depend directly on the new ctgan release! (see PR https://github.com/kasaai/ctgan/pull/7) :)

The only issue left is a cosmetic one, which I've filed here https://github.com/sdv-dev/CTGAN/issues/14

**Comment by kevinykuo** [comment]
Actually, a slightly less cosmetic issue here: https://github.com/sdv-dev/CTGAN/issues/16 :P

**Comment by kevinykuo** [comment]
@csala do you mind cutting a patch/minor release incorporating the last couple PRs so we can streamline the dependencies for the R package and get it on CRAN? Planning to tell people about SDV/CTGAN at the RStudio developer conference next week :)

**Comment by csala** [comment]
Sure, we'll go for it today @kevinykuo

> @csala I was able to cleanly remove the inline hacks and depend directly on the new ctgan release! (see PR [kasaai/ctgan#7](https://github.com/kasaai/ctgan/pull/7)) :)
> 
> The only issue left is a cosmetic one, which I've filed here #14

Great news btw! Thanks for taking care of it!

**Comment by csala** [comment]
[Release v0.2.1](/sdv-dev/CTGAN/releases/tag/v0.2.1) is out @kevinykuo !

The link to R package has also been added to the readme, so closing this.
