### ISSUE TITLE
Synthetic Generation Limits

### ISSUE THREAD

**Issue by Aditya-Agarwal-018** [sdv-dev/CTGAN#115]
* CTGAN version:
* Python version:
* Operating System:

### Description
Consider I am working on a classification problem, for this I have three questions:

1. Say I have:
    X_train_data = DataFrame of input features
    Y_train_data  = DataFrame of outputs linked to X_train_data

    When I will use CTGAN for data augmentation

    **ctgan = CTGANSynthesizer(epochs=10)  
       ctgan.fit(data, discrete_columns)**

    then here which option to use to define variable **data** in the code  
    **OPTION_1:**  data = pd.concat([X_train_data, Y_train_data]) 
       OR 
     **OPTION_2:**  data = X_train_data ?

      I had a doubt that if we use OPTION_2 then during the re-training of the MAchine Learning Model with 
      generated/synthetic/fake data we will not have any training labels linked to generated/synthetic/fake data.

2. What is the limit on the generated data by using real data that has N rows?
For example if we have a real training data of number of entries i.e. N_real=5000, then what is the maximum and minimum rows that is safe to generate the synthetic/fake using CTGAN?

3. How to generate synthetic7fake data from real data if there is no discrete column in real data?
    Code I am trying with:
    --------------CODE---------------------
    **discrete_columns = None

    ctgan = CTGANSynthesizer(epochs=10)
    ctgan.fit(data, discrete_columns)**
    --------------CODE---------------------
    But this given an error!
    ---------------------ERROR--------------------------------------
    ----> 2 ctgan.fit(df_all)

    ~.conda\envs\py3_jupyter\lib\site-packages\ctgan\synthesizers\ctgan.py in fit(self, train_data, discrete_columns, epochs)
    249 train_data = self._transformer.transform(train_data)
    250
    --> 251 self._data_sampler = DataSampler(
    252 train_data,
    253 self._transformer.output_info_list,

    ~.conda\envs\py3_jupyter\lib\site-packages\ctgan\data_sampler.py in init(self, data, output_info, log_frequency)
    40
    41 # Prepare an interval matrix for efficiently sample conditional vector
    ---> 42 max_category = max(
    43 [column_info[0].dim for column_info in output_info
    44 if is_discrete_column(column_info)])

    ValueError: max() arg is an empty sequence
    ---------------------ERROR--------------------------------------

Thanks!

**Comment by csala** [comment]
Hi @Aditya-Agarwal-018

First of all, I wanted to quickly remind you that SDV offers a user friendly wrapper around CTGAN which offers serveral advantages over using CTGAN as a standalone library, including the [CopulaGAN variation](https://sdv.dev/SDV/user_guides/single_table/copulagan.html) which in some cases provides superior data quality.

Regarding your first 2 questions:

1. If you Y is not constant (so, you are not fitting CTGAN with data from one class only), you should use OPTION_1 because of what you mention about OPTION_2: If you fit CTGAN with X only, the data that it will sample will be missing the Y labels, so you will not be able to use it to fit your ML models.

2. That limit depends on the dataset and on how well CTGAN captures the properties of your data. My suggestion would be to figure the number out empirically for each case, fitting and evaluating your models with different data sizes to get a notion of how much synthetic data they support before starting to be penalized by it.

**Comment by fealho** [comment]
For your third point, I just created a release candidate that fixes the issue. So if you run ```bash pip install ctgan==0.3.1.dev0``` it should work now.

I'll be closing the issue, since it seems all your questions have been answered.
