### ISSUE TITLE
TVAE: Code not properly capturing correlation between categorical and numerical columns

### ISSUE THREAD

**Issue by fealho** [sdv-dev/CTGAN#138]
If we run the code below, we will see that sampled correctly keeps the relationship between the categorical values ~99% of the time:  

```python
data = pd.DataFrame({
    '1': ['1.0', '2.0', '3.0'] * 150,
    '2': ['a', 'b', 'c'] * 150
})

tvae = TVAESynthesizer(epochs=300)
tvae.fit(data, ['1', '2'])

sampled = tvae.sample(1000)
```

However, if we change column 1 to be numerical, the model is unable to understand the relationship between the columns, and the matches are pretty much random:

```python
data = pd.DataFrame({
    '1': [1.0, 2.0, 3.0] * 150,
    '2': ['a', 'b', 'c'] * 150
})

tvae = TVAESynthesizer(epochs=300)
tvae.fit(data, ['2'])

sampled = tvae.sample(1000)
print(sampled.head(20))
```
This returns:

```
           1  2
0   3.008063  c
1   0.998053  a
2   2.989118  b
3   2.999388  b
4   2.989977  b
5   3.001034  a
6   3.002145  c
7   2.991087  a
8   1.998736  a
9   2.993332  a
10  2.987284  b
11  2.997205  c
12  3.003766  b
13  2.992854  b
14  1.995608  a
15  2.990174  b
16  2.991794  c
17  2.988642  b
18  2.988973  a
19  1.011714  b

```

**Comment by daniellawton99** [comment]
Any insights / progress on this one?
Thanks!

**Comment by npatki** [comment]
The initial comment prints out only the first 20 rows of synthetic data for manual inspection. I am unable to replicate this issue if I take a look at the overall distribution of the entire dataset.

Here is what I see if I treat both columns as categorical:
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/3227804/187766185-63fd32e2-d752-44e5-a2c3-12ba941b30bb.png">

Here is what I see if I treat the first column as numerical:
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/3227804/187766257-ae4c7317-9496-4fc1-8712-15d45fb682e2.png">

For purposes of comparison, I rounded the integers to the nearest whole numbers. While the combination of `'b', 2.0` is somewhat more common in the synthetic data, it seems seems that the TVAESynthesizer appropriately learned the correlation.  

If anyone else is encountering an issue with this, it would be helpful if you could share some quantifiable results. As it stands, I don't have enough evidence to conclude that there is any problem with TVAE capturing correlations.

**Comment by npatki** [comment]
Hi everyone, I'm going to close this issue off as stale since it does appear the correlations are being captured. As the original issue was filed over a year ago, perhaps there was a latent bug that has since been resolved?

Generally speaking, it's easier to model categorical columns over numerical ones, as there are a set # of values (categories). With numerical data, models have to expand and learn the full range of values -- even those that did not appear in the real data. 

However, it doesn't seem like numerical columns are far behind in terms of quality. If there are any specific metrics or datasets to look into, feel free to reply and I'll reopen the issue to investigate.
