### ISSUE TITLE
Do you support 3D data as inputs?

### ISSUE THREAD

**Issue by ItsyPetkov** [sdv-dev/CTGAN#167]
### Environment details

If you are already running CTGAN, please indicate the following details about the environment in
which you are running it:

* CTGAN version:
* Python version:
* Operating System:

### What I already tried

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @ItsyPetkov, the CTGAN is designed to work on tabular, 2 dimensional data. That is, a matrix of rows and columns.

If you have 3 dimensional data, some of the other models in the SDV library may be useful. For example the [PARSynthesizer](https://docs.sdv.dev/sdv/sequential-data/modeling/parsynthesizer) is able to handle **multi-sequence** data with 3 dimensions: An entity and a 2D sequence for each entity.

Since this is issue is about 2 years old, I'll mark it as closed. If you do have any follow ups or related requests, please feel free to file a new issue or drop us a comment [on Slack](https://bit.ly/sdv-slack-invite).
