### ISSUE TITLE
Not able to fit() CTGANSynthesizer() if NaNs are present in the dataset

### ISSUE THREAD

**Issue by rianboy18** [sdv-dev/CTGAN#21]
* CTGAN version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Hi @rianboy18 unfortunately CTGAN does indeed not work with null values.
Maybe this will change in the future, but for now it is intended to work only with single tables of numerical or categorical data, with no nulls.

If you want support for more complex scenarios, like nullable, boolean or datetime columns, or multi-table datasets, please have a look at the [SDV](sdv-dev/SDV) project.

Also note that, even though CTGAN is not yet available as an SDV model, work is currently being done in order to support it as well as other DL based synthesizers.

**Comment by rianboy18** [comment]
> Hi @rianboy18 unfortunately CTGAN does indeed not work with null values.
> Maybe this will change in the future, but for now it is intended to work only with single tables of numerical or categorical data, with no nulls.
> 
> If you want support for more complex scenarios, like nullable, boolean or datetime columns, or multi-table datasets, please have a look at the [SDV](sdv-dev/SDV) project.
> 
> Also note that, even though CTGAN is not yet available as an SDV model, work is currently being done in order to support it as well as other DL based synthesizers.

Thanks @csala. Noted !
