### ISSUE TITLE
Protected-like attribute in CTGANSynthesizer

### ISSUE THREAD

**Issue by davebulaval** [sdv-dev/CTGAN#218]
Is there a particular reason why `CTGANSynthesizer` uses protected attributes?

If not, I propose to change it to normalize the attribute naming style.

**Comment by npatki** [comment]
From a quick glance at the `CTGANSynthesizer` code, it doesn't seem to be declaring attributes any differently than the rest of the SDV ecosystem. If you are able to point to particular lines of code that are inconsistent, we can take a look. Otherwise, it is currently out of scope for us to redefine our code style.

**Comment by davebulaval** [comment]
I can open a PR with the fixes on TVAE to use protected-like attributes.
