### ISSUE TITLE
Quick usage not working

### ISSUE THREAD

**Issue by martabatlle94** [sdv-dev/CTGAN#241]
Hi,

I have only followed the steps I found in the quick usage page: https://sdv.dev/SDV/user_guides/single_table/ctgan.html

I installed ctgan and imported it. I also import my dataset (df). Then I run:

model = CTGAN()
model.fit(df)

And I get an error: TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 3 keyword-only arguments) were given

I get the same error using your dataset example (student_placements).

Thanks,

Marta

**Comment by npatki** [comment]
Hi @martabatlle94,

Unfortunately, I am not able to replicate what you're observing. It would be great if you can share the full stack trace and any other relevant parts of your code (import statements, the way you're loading in your dataset, etc.).

It would also be helpful to check the following items --

1. Installation: What version of CTGAN and SDV do you have installed? 
```python
import sdv
import ctgan

print(sdv.__version__)
print(ctgan.__version__)
```

2. Demo Dataset: Can you replicate this issue using the `demo` dataset rather than your own? 
```python
from sdv.demo import load_tabular_demo
from sdv.tabular import CTGAN

data = load_tabular_demo('student_placements')

model = CTGAN()
model.fit(data)
```

**Comment by npatki** [comment]
Hi @martabatlle94, I'm closing this issue off as unable to replicate.

If you're still continuing to experience this bug after checking the installation and demo dataset, please feel free to reply and I will re-open the issue to investigate.
