### ISSUE TITLE
SDV Compatibility with a specific CTGAN and Torch versions

### ISSUE THREAD

**Issue by dsrishti** [sdv-dev/CTGAN#249]
Hi Team,

Is there an SDV version that works with ctgan 0.4.3 and torch 1.12.1+cu102? I am asking this because we want an SDV version that can work along with [OpenDP ](https://github.com/opendp/smartnoise-sdk)package

**Comment by npatki** [comment]
Hi @dsrishti, you can find the requirements for CTGAN 0.4.3 [here](https://github.com/sdv-dev/CTGAN/blob/v0.4.3/setup.py). 

If this does not suit your needs, I wonder if you can consider upgrading your version of CTGAN? The 0.4.3 release is over a year old. We've added some features -- and updated versioning requirements -- since then.
