### ISSUE TITLE
sdv and ctgan not synchronized w.r.t. CTGAN()

### ISSUE THREAD

**Issue by shimonrm** [sdv-dev/CTGAN#255]
While ctgan.CTGAN() has been updated to 0.6.0, sdv.tabular.CTGAN still wraps version 0.5.2.

**Comment by npatki** [comment]
Hi @shimonrm, thanks for the heads up!

Our ecosystem is set up in a way that allows us to update our libraries separately. The only major change between `0.6.0` and `0.5.2` is renaming a few classes. So rest assured that you aren't missing out on any core functionality if you're using CTGAN through the `sdv.tabular` wrapper!

A future version of SDV should correctly wrap around CTGAN `0.6.0`. I'll reclassify this issue as a question since it's not exactly a bug to have our libraries on different versions. Let me know if you have any more thoughts!

**Comment by npatki** [comment]
Update: I've filed an issue in the SDV library to track this just in case 

https://github.com/sdv-dev/SDV/issues/1112

You can follow along in the issue for a fix. In the meantime, I'll close this one as resolved. Please feel free to reply if there is anything more to discuss and I can reopen the issue.
