### ISSUE TITLE
How to create a column with CTGAN

### ISSUE THREAD

**Issue by NaHyun111** [sdv-dev/CTGAN#278]
### Environment details

If you are already running CTGAN, please indicate the following details about the environment in
which you are running it:

* Python version: 3.9.13
* Operating System: vscode

### Problem description

**When data is generated with CTGAN, the row increases.
But I also wonder if there is a way to increment a column.
Does anyone know how?**

**Comment by npatki** [comment]
Hi @NaHyun111, nice to meet you! Would you be able to explain a bit more about your use case? What kind of data do you have and what do the rows/columns represent?

The CTGAN model (as well as the overall SDV ecosystem) is designed to work on tabular data, where the columns represent fixed attributes (eg. `email`, `payment_amount`, `address`, etc.) and the rows represent different entities (eg. users). That's why we are easily able to create new rows -- as we are creating synthetic entities. However, creating new columns is not very well defined. It's unclear which new attributes to add.

[Here's an example of a single table dataset](https://docs.sdv.dev/sdv/single-table-data/data-preparation). 

Let me know if this helps.

**Comment by NaHyun111** [comment]
Hi! @npatki thank you for replying :)
I fully understood what you said.
It was understood that it was difficult to add a column because it was not clear what property it was adding.

thanks for the help. Have a nice day!
