### ISSUE TITLE
Min/max in metadata not used

### ISSUE THREAD

**Issue by kevinykuo** [sdv-dev/CTGAN#3]
Is the min/max info supposed to be used anywhere? https://github.com/DAI-Lab/CTGAN/blob/7aa29685045ffdba84bd87432354c133e05699e6/ctgan/ctgan_model.py#L59-L60

**Comment by leix28** [comment]
Min/max info is not used in our model. Continuous columns are preprocessed by Variational Gaussian Mixture (VGM) instead of min-max normalization. VGM can automatically adapt to columns with different range and distribution. So the min/max info is not necessary. 

The generated synthetic data usually fits in the min-max range. But it's also possible to use min-max info to post-process generated data.
