### ISSUE TITLE
Tracking and Saving TVAE Loss Values

### ISSUE THREAD

**Issue by gjuresic** [sdv-dev/CTGAN#307]
### Environment details

* CTGAN version: 0.7.3
* Python version: 3.9.6
* Operating System: macOS

### Problem description

When fitting CTGAN, I can capture the loss values in the output variable. However, the same cannot be implemented when fitting the TVAE. How can I track and store the loss values to see if the model is able to learn the distribution of the data over the selected number of epochs?

**Comment by npatki** [comment]
Hi @gjuresic, currently it is not possible to track the loss values very easily although we have an outstanding feature request for it at #300. You can review the proposed functionality there and let us know if it will meet your needs.

In the meantime, there are still other options for seeing if the model learned distributions. One possible approach:
1. Sample synthetic data from the fitted synthesizer
2. Use the [SDMetrics library](https://docs.sdv.dev/sdmetrics/) to compare the real vs. synthetic data. If the synthesizer learned the distributions well, it should report high scores.
3. You can also run a [Quality Report](https://docs.sdv.dev/sdmetrics/reports/quality-report) and create [visualizations](https://docs.sdv.dev/sdmetrics/reports/visualization-utilities#compare-a-synthetic-column-and-real-column-1d) to manually inspect the data.

Hopefully that helps! Let me know if you have any follow ups, but otherwise, I'd defer to issue #300 for the implementation that we want to add.

**Comment by npatki** [comment]
This feature has now been added. For API, see #300. Thanks.
