### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by chaotianshinaida** [sdv-dev/CTGAN#321]
How are hyperparameters selected? Why do you don't select  hpyerparameter?

**Comment by srinify** [comment]
Hi there @chaotianshinaida 👋 This is a super delayed response but we've since brought CTGAN into SDV and added lots of affordances & ergonomics to improve the user experience: https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer

- You can read our docs [here](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#how-do-i-tune-the-hyperparameters-such-as-epochs-or-other-values) to learn more about how to tweak the hyperparameters a little bit. This is a tough area for sure.
- I'd also encourage you to check out [GaussianCopulaSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer) as a faster, more tunable, and more interpretable alternative to CTGAN

I'm closing this issue for now but let me know if you have more quetsions!
