### ISSUE TITLE
Tune about CTGAN

### ISSUE THREAD

**Issue by zealscott** [sdv-dev/CTGAN#325]
### Environment details

If you are already running CTGAN, please indicate the following details about the environment in
which you are running it:

* CTGAN version: 0.8
* Python version: 3.9
* Operating System: Linux

### Problem description

I am insterested in how to tune CTGAN so that it can be used on other tabular data. I already tried to use the default settings for other datasets, and mostly they work well. But I want to know how to tune the hyperparameters (epochs, batch_size, lr, etc) to get the best possible results for any given datasets? It seems the tuning process is not mentioned in the paper.

Thanks and looking forward to your reply!

**Comment by srinify** [comment]
Hi there @zealscott 👋 A few suggestions to explore!

**Gaussian Copulas**
Because GAN's in general are hard to tune, we created a gaussian copula based alternative that's faster, easier to tune, and is more interpretable in general. [That synthesizer is part of SDV,](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer) which is our framework that's situated one level above our individual model libraries like CTGAN and copulas. You can take it for a spin in just a few lines of code so something to explore!

**CTGANSynthesizer**
We have a [CTGANSynthesizer class](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#faqs) in SDV and some people have achieved better model quality and better synthetic data quality just by switching from the CTGAN library to this class in SDV. We do some extra [data pre-processing ](https://docs.sdv.dev/sdv/single-table-data/modeling/customizations/preprocessing)so that can help CTGAN converge on better results!

**Tuning CTGAN**
Tuning GAN's is a bit of an art. You could use a hyperparameter exploration library like [BTB](https://github.com/MLBazaar/BTB). It's unaffiliated with DataCebo and we're not experts in the library, but something to explore as well.

**Comment by zealscott** [comment]
Thank for your suggestion @srinify !

**Comment by srinify** [comment]
Sure thing @zealscott let us know if these end up working for you!
