### ISSUE TITLE
TypeError while ctgan.fit()

### ISSUE THREAD

**Issue by AT9991** [sdv-dev/CTGAN#326]
### Environment Details
Google Colab 

### Error Description

TypeError                                 Traceback (most recent call last)
[<ipython-input-21-c7edb24a3296>](https://uw086u38ter-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240103-060134_RC00_595368506#) in <cell line: 1>()
----> 1 ctgan.fit(trial)

6 frames
[/usr/local/lib/python3.10/dist-packages/rdt/transformers/base.py](https://uw086u38ter-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240103-060134_RC00_595368506#) in _set_seed(self, data)
    365         hash_value = self.columns[0]
    366         for value in data.head(5):
--> 367             hash_value += str(value)
    368 
    369         hash_value = int(hashlib.sha256(hash_value.encode('utf-8')).hexdigest(), 16)

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

### Steps to reproduce
!pip install ctgan
from ctgan import CTGAN
data = pd.read_csv(...)
ctgan = CTGAN(epochs=100)
ctgan.fit(data)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by aarishmaqsood** [comment]
I was facing the same problem. There may be a problem with your column names, they should be strings.

**Comment by npatki** [comment]
Hi @AT9991 and @aarishmaqsood, would either of you be able to share some CSV data that we can use to replicate this?

BTW instead of using the CTGAN library directly, I would highly recommend using the SDV library. You can access the [CTGAN Synthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer) via SDV. Doing so will allow you to make use of additional features -- such as better data pre-processing, customizations such as constraints, and conditional sampling. 

I actually wonder whether you would still encounter this bug in SDV, since there is a lot more data validation and checking we do there. [Here is a tutorial](https://colab.research.google.com/drive/15iom9fO8j_gHg4-NlGkzWF5thMWStXwv?usp=sharing) that uses CTGAN via the SDV library.

**Comment by aarishmaqsood** [comment]
@npatki Thank you for your response. I have fixed my problem. In the future I will use your suggested solution.

**Comment by npatki** [comment]
Great to hear @aarishmaqsood. Could you describe what fixed your problem? In case other others have the same issue, I can refer them here. Thanks.
