### ISSUE TITLE
Documentation: Guidance about picking hyperparameters

### ISSUE THREAD

**Issue by turian** [sdv-dev/CTGAN#51]
* CTGAN version: v0.2.1
* Python version: 3.7.7
* Operating System: OSX 10.14.6

### Description

I am working with a new tabular dataset where it is difficult to evaluate the results.

It has about 2500 rows and 40 columns.

It is difficult to know how to evaluate the model or what hyperparameters to use. Can you provide some guidance in the documentation? For example, is minimizing the loss of G and D the goal? Or what evaluation methods should be used?

**Comment by leix28** [comment]
Hi, 

Measuring the performance of GAN is challenging in general. The loss is not a good indicator for model performance. (But make sure losses are in a reasonable range, like [-100, 100].)

You can focus more on the downstream performance if you have a downstream application. Otherwise, you can (1) visualize the marginal distribution of columns; (2) measure the correlation between columns. 

The dataset is relatively small. Choosing a smaller number of layers and smaller layer size may be better.

**Comment by csala** [comment]
Closing this issue because it has already been responded. Please feel free to re-open if there are any further doubts about it.
