### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by kvrameshreddy** [sdv-dev/CTGAN#61]
* CTGAN version: v0.2.1 - 2020-01-27
* Python version: 3.7
* Operating System: Windows 8.1

### Description

I need to generate table data similar to input. The input data has two columns like "Company" and "Dept"
CTGAN is generating data randomly. But i need data Specifically like company1 has 4 Departments Which are unique.
When Ever CTGAN Generate data row with company 1 the Department Column should be filled with the 4 unique Departments.

Please help me if there is a way to solve this. 

### What I Did

![question](https://user-images.githubusercontent.com/49742709/87793490-f8846d80-c862-11ea-9ed7-e3889d12a3dc.JPG)

**Comment by oregonpillow** [comment]
What you're asking isn't possible. Although CTGAN can detect relationships between columns it's still going to sample from a distribution. It might learn that Comp1 should have a much higher probability of being A,B,C and that Comp2 is likely X,Y,Z but it doesn't know that these are hard and fast rules.

My suggestion would be 1) Create a large enough sample for your needs and trim off any rows where Comp1 is X,Y,Z for example or Comp2 is A,B,C. Or 2) synthesise data independently then combine the datasets. E.g synthesize on Comp1 dataset, another for Comp2. Sample from both them combine the results.

**Comment by kvrameshreddy** [comment]
thank you

**Comment by kvrameshreddy** [comment]
can any other model does the above use case. please suggest me.

**Comment by oregonpillow** [comment]
> can any other model does the above use case. please suggest me.

Mmmm not that I'm aware of. Your use case is pretty specific in terms of what you want. All models that i know of rely on Gaussian mixture models to sample from distributions. I don't know if your goal is to have more data or to have synthetic data that can be shared more freely. If you're only interested in privacy then I'd look at Differential Privacy models.

Otherwise you can try https://github.com/DataResponsibly/DataSynthesizer

or perhaps https://github.com/sdv-dev/Copulas 

I'm not too familiar with relational databases but it seems maybe your problem could be set up as if it was part of a relational dataset, in which case you could try:

https://github.com/sdv-dev/SDV

**Comment by kvrameshreddy** [comment]
thank you very much. I have tried DataSynthesizer. still facing the same issue. Will check with Copulas

**Comment by csala** [comment]
Hello @kvrameshreddy 

As @oregonpillow pointed out, your best bet will be to try [SDV](/sdv-dev/SDV).

SDV works with both multi-table and single table datasets (time-series coming _very_ soon) and it wraps both Copulas and CTGAN to provide a user-friendly interface that handles all these things for you, as well as data types, missing data, etc. The particular feature that you are asking for is what we call a _Constraint_ and will be added as a new feature in the upcoming days, probably this week. You can follow the progress of the development [here](https://github.com/sdv-dev/SDV/issues/169).

As an interim workaround, while SDV does not handle it automatically, what you can do in a situation like yours is to merge the two columns together into a single column (i.e. create a column called `company_dept`, which contains the values `<company>#<dept>`), and then separate it back into two columns after sampling. This will respect the company+dept combinations while also capturing their joint distribution with the other columns.

**Comment by kvrameshreddy** [comment]
Thank you.  I will Check with SDV.

**Comment by kvrameshreddy** [comment]
Can you help with the execution of SDV for single table datasets.

**Comment by csala** [comment]
Sure, we'll try. Please feel free to open an issue directly in SDV it the question is related to it.

**Comment by kvrameshreddy** [comment]
Sure. Thank you @csala

**Comment by kvrameshreddy** [comment]
Hi @csala 
Is there any upcoming enhancement that adding "constraint"  in 'CTGAN' same as you developed in 'SDV'

**Comment by csala** [comment]
Closing this issue, as the doubt has been already resolved.

> Hi @csala
> Is there any upcoming enhancement that adding "constraint" in 'CTGAN' same as you developed in 'SDV'

No, we recommend using CTGAN through SDV, so you can access to both the constraints and all the other enhancements that SDV offers.

**Comment by npatki** [comment]
Hi @Abhishek967026, I don't know if your problem is related to this issue. I'd be happy to help if you can file a new issue in the [SDV library](https://github.com/sdv-dev/SDV/issues/new/choose) describing your problem. Alternatively, you can also join our Slack at https://bit.ly/sdv-slack-invite and ask your Q there.

**Comment by npatki** [comment]
@sushantpawar-navikenz -- I believe Carles was referring to the constraints functionality. You can go through [this user guide](https://sdv.dev/SDV/user_guides/single_table/handling_constraints.html) to apply them.
